_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]
    ASPECT_RATIOS: [[0.25, 0.5, 1.0, 1.25, 2.0]]
  RPN:
    NMS_THRESH: 0.7
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WARMUP_ITERS: 500
  BASE_LR: 0.00025
OUTPUT_DIR: "exp/R_50_FPN_3x_ratio"
DATALOADER:
  NUM_WORKERS: 12

# INPUT:
#   MIN_SIZE_TRAIN: (800,)
# # Sample size of smallest side by choice or random selection from range give by
# # INPUT.MIN_SIZE_TRAIN
# MIN_SIZE_TRAIN_SAMPLING: "choice"
# # Maximum size of the side of the image during training
# MAX_SIZE_TRAIN: 1333
# RANDOM_FLIP: "none"

