_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True] # Deformable
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    NMS_THRESH: 0.7
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WARMUP_ITERS: 500
  BASE_LR: 0.00025
OUTPUT_DIR: "exp/R_50_FPN_3x_3deforamable"
DATALOADER:
  NUM_WORKERS: 12

