AdamW:
  _target_: torch.optim.AdamW
  betas: [0.9, 0.999]
  lr: 0.0001
  params: {_target_: detectron2.solver.get_default_optimizer_params, base_lr: '${..lr}', weight_decay_norm: 0.0}
  weight_decay: 0.1
SGD:
  _target_: torch.optim.SGD
  lr: 0.02
  momentum: 0.9
  params: {_target_: detectron2.solver.get_default_optimizer_params, weight_decay_norm: 0.0}
  weight_decay: 0.0001
